services:
  app-contrasenas:
    build: .
    container_name: gestor_contrasena_app
    ports:
      - "3017:3017"
    volumes:
      - .:/app
      - /app/node_modules
      # Volumen persistente para la base de datos (fuera del código)
      - db_data:/app/data
    env_file:
      - .env
    restart: always

volumes:
  db_data:
